// <auto-generated />
using System;
using AlumnosApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlumnosApi.Migrations
{
    [DbContext(typeof(EscuelaContext))]
    [Migration("20250814041401_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AlumnosApi.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreAlumno")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreMadre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombrePadre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Seccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Alumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
